version: "3"

dotenv:
  - ./targets/docker/.env

env:
  TARGETS_DIR: ./targets
  SERVICES_DIR: ./services
  SCRIPTS_DIR: ./scripts

  PROJECT_NAME: '{{.PROJECT_NAME | default "orekit"}}'
  COMPOSE_PROJECT_NAME: '{{.COMPOSE_PROJECT_NAME | default "orekit"}}'

  CONTAINER_BIN: docker
  CONTAINER_COMPOSE_BIN: " {{.CONTAINER_BIN}} compose "

  CONTAINER_DIR: "{{.TARGETS_DIR}}/docker"
  COMPOSE_FILE: "{{.CONTAINER_DIR}}/compose.yaml"

  DEPLOYMENT_ENVIRO: '{{.DEPLOYMENT_ENVIRO | default ""}}'
  HTTP_PROXY: '{{.HTTP_PROXY | default ""}}'
  HTTPS_PROXY: '{{.HTTPS_PROXY | default ""}}'

  ENVIRO_SCRIPT: "{{.SCRIPTS_DIR}}/env.sh"
  ENVIRO_FILE: "{{.CONTAINER_DIR}}/.env"

  MAVEN_HTTPS_PROXY: '-s./settings.xml'
  MAVEN_SETTINGS_FILE: '{{.MAVEN_SETTINGS_FILE | default ""}}'

tasks:
  default:
    desc: Shows this help message
    cmds:
      - task --list-all
    silent: true

  env-create:
    desc: Create .env file from env.sh script
    cmds:
      - |
        ${ENVIRO_SCRIPT} > ${ENVIRO_FILE}

  build:
    desc: Build Orekit service container
    deps:
      - env-create
    cmds:
      - |
        source ${ENVIRO_FILE} && \
          ${CONTAINER_COMPOSE_BIN} -f ${COMPOSE_FILE} build orekit
