#!/usr/bin/env bash

# A script to generate .env file for container deployments
PROJECT_NAME=orekit
COMPOSE_PROJECT_NAME=orekit

cat << EOF
#
# Auto-generated by ${PWD}/$(basename $0) on $(date -u +"%Y-%m-%dT%H:%M:%S%z")
#
IMAGE_URI=maven:3.9.9-eclipse-temurin-17

# Deployment specific configurations
DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}
HEALTHCHECK_PORT=${HEALTHCHECK_PORT}

# Proxy configurations, the proxy values come for the environment, 
# which is important for the vmmoc
HTTPS_PROXY=${HTTPS_PROXY}
HTTP_PROXY=${HTTP_PROXY}
NO_PROXY=${NO_PROXY}

PROJECT_NAME=${PROJECT_NAME}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}

# Maven/Java specific configurations
MAVEN_REPO_LOCAL=/home/${PROJECT_NAME}/.${PROJECT_NAME}/.m2
MAVEN_HTTPS_PROXY="--settings ./settings.xml"
MAVEN_SETTINGS_FILE=${MAVEN_SETTINGS_FILE}

# Orekit specific configurations

OREKIT_USER=${PROJECT_NAME}

# Orekit git specific configurations
OREKIT_GIT_URL=https://gitlab.orekit.org/orekit/orekit.git
OREKIT_GIT_COMMIT=develop

# Orekit data specific configurations
OREKIT_DATA_GIT_URL=https://gitlab.orekit.org/orekit/orekit-data.git
OREKIT_DATA_GIT_COMMIT=develop

# Orekit dependencies configurations
HIPPARCHUS_GIT_URL=https://github.com/Hipparchus-Math/hipparchus.git
HIPPARCHUS_GIT_COMMIT=develop

OREKIT_BASE_DIR=/opt/gitlab.orekit.org/orekit

EOF
